#!/bin/bash
cd "$(dirname "$0")"
set -e

rg_name="$1"
params_path="$2"

if [[ -z "$rg_name" ]]; then
    echo "Please provide a name for the Azure resource group."
    exit 1
fi

if [[ -z "$params_path" ]]; then
    echo "Please provide valid path to a '.bicepparam' file."
    exit 1
fi

rg_exists=$(az group list | jq --arg rg_name "$rg_name" 'map(select(.name == $rg_name)) | any')

if [[ $rg_exists = "true" ]]; then
    echo "Resource group '$rg_name' already exists."
else
    echo "Creating resource group '$rg_name'."
    az group create --name "$rg_name" --output none
fi

echo "Deploying resources."
az deployment group create \
    --resource-group "$rg_name" \
    --template-file ../azure/main.bicep \
    --parameters "${params_path}" \
    --output none
echo "Done."
