#!/bin/bash

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

echo "Installing azure-storage-backup..."

dotnet publish ../AzureBackupTool/AzureBackupTool.csproj \
    --configuration Release \
    --self-contained \
    --runtime linux-x64 \
    --output /opt/AzureBackupTool

ln --force --symbolic /opt/AzureBackupTool/AzureBackupTool /usr/local/bin/azure-storage-backup

# create sqlite database in /var/lib/azure-storage-backup
mkdir --parents /var/lib/azure-storage-backup
if [[ ! -f /var/lib/azure-storage-backup/source.db ]]; then
    echo "Initialising database..."
    ./create-db /var/lib/azure-storage-backup/source.db
else
    echo "Existing database detected."
fi

# create config directory in /etc/azure-storage-backup
mkdir --parents /etc/azure-storage-backup
file="/etc/azure-storage-backup/appsettings.json"
if [[ -f /etc/azure-storage-backup/appsettings.json ]]; then
    echo "Found existing appsettings file."
    echo "appsettings.new.json must be checked for required merges."
    file="/etc/azure-storage-backup/appsettings.new.json"
fi

cp /opt/AzureBackupTool/appsettings.json "${file}"
